### ISSUE TITLE
Can I train PiPa with more than one GPU?

### ISSUE THREAD

**Issue by wengkai0** [chen742/PiPa#11]
Hi, 

Thanks for your great work!
I am doing a research project and I would like to adopt your model as my baseline, but I would like to know if this model could only be trained on one GPU.

**Comment by chen742** [comment]
Thanks for your interesting in our work!

We do not support training with more than one GPUs, but the instructions on how to perform Multi-GPU training can be found in the mmsegmentation repository. 

Mu
