### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by kuangsoh** [chen742/PiPa#12]
Hi authors,

I installed the codebase following your instruction, but got the below error, 
could you helpme ? any suggestion is good.

"RuntimeError: nms is not compiled with GPU support"

Thanks

**Comment by chen742** [comment]
Thanks for your interest in our work.

This error is because your CUDA environment is not installed correctly. You may try to re-install your CUDA environment and then delete the build/ folder before re-compile mmcv.

Mu
