### ISSUE TITLE
About GPU device

### ISSUE THREAD

**Issue by sibo888** [chen742/PiPa#2]
Dear authors,

Thanks for your impressive work and code for the community, I am a student studying your paper and your work inspires me a lot. 

I want to learn more about your work by running the code. Could I train it with my 3080 GPU (laptop)？Do I need to use more GPUS for distributed?

**Comment by chen742** [comment]
Hi,

Thanks for your interest in our work! 

If you change the batch size to 1, you could run the code successfully with Nvidia 3080 laptop with 16G memory. We do not use distributed training for this project.

Kindly Regards
Mu

**Comment by sibo888** [comment]
Thank you
