### ISSUE TITLE
patch loss

### ISSUE THREAD

**Issue by wzlyyb** [chen742/PiPa#3]
Why your patch loss use the feature of teacher network？And how to train your self.classifier in dacs.py？

**Comment by wzlyyb** [comment]
![image](https://user-images.githubusercontent.com/87351932/209509007-61c556e0-8605-4b8d-af3a-b24e1478177d.png)

**Comment by wzlyyb** [comment]
![image](https://user-images.githubusercontent.com/87351932/209509074-58825fac-c66c-4c77-a31f-4882e2bc4536.png)

**Comment by zan-wang** [comment]
> Why your patch loss use the feature of teacher network？And how to train your self.classifier in dacs.py？

Bro, did you get this doubt solved? I also want to know why use teacher model.

**Comment by super233** [comment]
I'm also curious about this. The gain of performance may be caused by Teacher model, which is updated by BP (back propagation) but not EMA (expotional moving average). Could you please explain the reason? @chen742 

Have you tried patch loss based on feature of student model? @wzlyyb

**Comment by zyuanbing** [comment]
@super233 Actually, the teacher model has no gradient flow.
https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/mmseg/models/uda/dacs.py#L136-L138
Patch loss may has not been applied in this code.

**Comment by wzlyyb** [comment]
> 



> @super233 Actually, the teacher model has no gradient flow.
> 
> https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/mmseg/models/uda/dacs.py#L136-L138
> 
> 
> Patch loss may has not been applied in this code.

I agree it

**Comment by super233** [comment]
> @super233 Actually, the teacher model has no gradient flow.
> 
> https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/mmseg/models/uda/dacs.py#L136-L138
> 
> 
> Patch loss may has not been applied in this code.

Thanks for your reply. Then why your patch loss use the feature of teacher network?

**Comment by wzlyyb** [comment]
> > @super233 Actually, the teacher model has no gradient flow.
> > https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/mmseg/models/uda/dacs.py#L136-L138
> > 
> > Patch loss may has not been applied in this code.
> 
> Thanks for your reply. Then why your patch loss use the feature of teacher network?

Because I am not author. I also wait for the replay of the author.

**Comment by super233** [comment]
> > > @super233 Actually, the teacher model has no gradient flow.
> > > https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/mmseg/models/uda/dacs.py#L136-L138
> > > 
> > > Patch loss may has not been applied in this code.
> > 
> > 
> > Thanks for your reply. Then why your patch loss use the feature of teacher network?
> 
> Because I am not author. I also wait for the replay of the author.

@chen742

**Comment by chen742** [comment]
> > > > @super233 Actually, the teacher model has no gradient flow.
> > > > https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/mmseg/models/uda/dacs.py#L136-L138
> > > > 
> > > > Patch loss may has not been applied in this code.
> > > 
> > > 
> > > Thanks for your reply. Then why your patch loss use the feature of teacher network?
> > 
> > 
> > Because I am not author. I also wait for the replay of the author.
> 
> @chen742

Hi @super233 , in our code, we use the teacher branch to perform patch loss for the ablation study, as [zyuanbing] says, there is no gradient flow in the teacher branch you could generate features from the student branch. We will provide the updated code soon

**Comment by kaigelee** [comment]
> Why your patch loss use the feature of teacher network？And how to train your self.classifier in dacs.py？

请问您知道了吗？ 
另外，我也没找到作者是如何训练self.cls_head in encoder_decoder.py的。 请问您发现了吗
