### ISSUE TITLE
Can I generate realistic images instead of segmentation masks?

### ISSUE THREAD

**Issue by At-Walid** [chen742/PiPa#5]
Hello,

I wanted to know if it's possible to generate realistic images (like cityscape images) instead of segmentation masks? 

Thanks

**Comment by chen742** [comment]
Thanks for your interest in our work!

Generating real images is not supported till now, we would consider adding this function in the future

Kindly Regards
Mu

**Comment by DenisN03** [comment]
Hi! You have a very rewarding job. Is it possible now to generate realistic images?
