### ISSUE TITLE
Code of DAFormer + PiPa

### ISSUE THREAD

**Issue by super233** [chen742/PiPa#6]
Hi, thanks for your awesome code.

I noticed that the released code is disigned for HRDA, could you please provide the code for DAFormer?

**Comment by chen742** [comment]
Thanks for your interest in our work!

We also support  PiPa based on DAFormer, please check PiPa/PiPa_DAFormer (Subfolder) for more details

Kindly Regards
Mu

**Comment by super233** [comment]
Thanks
