### ISSUE TITLE
Questions about embedding features for contrastive learning

### ISSUE THREAD

**Issue by super233** [chen742/PiPa#8]
Hi, thanks for your sharing codes, it's really an awesome work for UDA.

I have noticed that the embedding features for “Source Pixel Contrast” and "Target Patch Contrast" are not the same.

Concretely, embedding features for “Source Pixel Contrast” are obtained by concatenating 4 features from the backbone by yourself.
https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/PiPa_DAFormer/mmseg/models/segmentors/encoder_decoder.py#L174-L181

However, embedding features for “Target Patch Contrast” are directly obtained from the `fuse_layer`
https://github.com/chen742/PiPa/blob/4eb532e9d8e4f62029ecba04a1e3fecc5f65f7a6/PiPa_DAFormer/mmseg/models/decode_heads/daformer_head.py#L176-L180

Why not use the same embedding features?

**Comment by chen742** [comment]
Hi,

Thanks for your interest in our work.
According to our experiment, we find that concatenating source features provides more gain in the results. (although minor) You could also try to use the same process to fuse features.

Kind Regards
Mu
